### ISSUE TITLE
[BUG] Games without submissions crash app.

### ISSUE THREAD

**Issue by n0w33d** [PoloNX/SimpleModDownloader#39]
**Describe the bug**
For unknown reasons, attempting to browse mods for the following games will crash the application.

**On which mod**
[The Long Dark](https://gamebanana.com/games/5989)

Roller Coaster Tycoon 3 Complete Edition

[Spelunky 2](https://gamebanana.com/games/8538)

[Grand Theft Auto Definitive Edition](https://gamebanana.com/games/14891)

Assassins Creed The Rebel Collection

[Star Wars The Force Unleashed](https://gamebanana.com/games/7711)

[Star Wars Knights of the Old Republic
](https://gamebanana.com/games/1623)

[Star Wars Jedi Knight 2 Jedi Outcast](https://gamebanana.com/games/14684)

**To Reproduce**
1. Go to any of the listed games in SimpleModDownloader
2. Click on any of the listed games.
3. See no error, system hangs indefinitely unless Home button is pressed and application is forced closed. 

**Expected behavior**
A list of mods or an error prompt should appear. 

**Switch:**
 - Horizon Os version 16.1.0|AMS 1.5.5|E
 - SimpleModDownloader version 1.0.3

**Additional context**
N/A

**Comment by LokeYourC3PH** [comment]
There's also the issue that with games that do work, the Downloader is cripplingly slow at showing the menu. It takes anywhere between 5 to 10 minutes, or sometimes even longer or it doesn't load at all. The way this can be handled is by, instead of loading the entire available mods list from GameBanana, load it chunk wise, always only by like 10 or so. That way, the system won't be overloaded, and it will actually show mods as well. A good example of this is when I go into Pokémon Legends: Arceus. It simply takes forever to load and so I just give up and to it manually.

**Comment by PoloNX** [comment]
Fixed
